package com.ghostbot.mapNavigation

/**
 * Port of GhostBot/map_navigation.py — the zone table and location->zone map.
 */
data class Zone(
    val location: String,
    val boundary: Pair<Pair<Int, Int>, Pair<Int, Int>>,
    val centre: Pair<Int, Int>,
    val scale: Pair<Double, Double>,
)

val zones: Map<String, Zone> = mapOf(
    "simen_mountain" to Zone("simen_mountain", (1270 to 1800) to (2030 to 1280), 1667 to 1544, -1.05 to 1.2),
    "barbarian_mountain" to Zone("barbarian_mountain", (1281 to 1280) to (2050 to 510), 1667 to 902, -1.0 to 1.2),
    "green_scarp" to Zone("green_scarp", (280 to 1500) to (500 to 760), 456 to 1164, -1.05 to 1.65),
    "sky_village" to Zone("sky_village", (250 to 760) to (515 to 0), 150 to 404, -1.5 to 1.85),
    "cloud_mountain" to Zone("cloud_mountain", (-200 to 220) to (760 to -266), 257 to 45, -1.4 to 1.5),
    "stone_city" to Zone("stone_city", (-70 to -266) to (490 to -760), 217 to -528, -1.0 to 1.2),
    "black_wind_camp" to Zone("black_wind_camp", (-762 to -270) to (-60 to -760), -415 to -497, -1.0 to 1.1),
    "laurel_mountain" to Zone("laurel_mountain", (-770 to -770) to (-260 to -1500), -489 to -1125, -1.45 to 1.65),
    "snow_mountain" to Zone("snow_mountain", (-1270 to -780) to (-1075 to -1275), -1009 to -1012, -0.95 to 1.2),
    "whorl_mountain" to Zone("whorl_mountain", (-1260 to -1275) to (-800 to -2020), -1001 to -1639, -1.5 to 1.5),
    "vast_mountain" to Zone("vast_mountain", (491 to -280) to (1540 to -410), 989 to -489, -1.38 to 1.38),
    "dais_field" to Zone("dais_field", (1540 to -20) to (3070 to -750), 2304 to -453, -2.05 to 2.05),
)

private val zoneMap: Map<String, List<String>> = mapOf(
    "peace_island" to listOf("Moon Dragon Harbor", "Black Turtle Palace", "Coconut Woods", "Peace Village"),
    "simen_mountain" to listOf(
        "Bandit Lair",
        "Bandit Fort",
        "East of Simen Mountain",
        "Moon Dragon Village",
        "Outskirt of Village",
        "South of Simen Mountain",
    ),
    "west_simen_mountain" to listOf("Dry Woods", "Old Site of Village", "West of Simen Mountain"),
    "green_scarp" to listOf(
        "Green Scarp",
        "Piedmont of Green Scarp",
        "Green Scarp Secret Cave",
        "Back Mountain of Green Scarp",
    ),
    "sky_village" to listOf(
        "Sky Village",
        "Sky Village Field",
        "Hiking Road",
        "South Wasteland",
        "Sky Village North East",
        "Sky Village South East",
        "Sky Village South West",
        "South Suburb of Sky Village",
        "North Suburb of Sky Village",
        "East Suburb of Sky Village",
        "West Suburb of Sky Village",
        "Snake Swamp",
        "Snake Swamp South",
        "Snake Swamp North",
        "Black Campo",
        "Black Campo West",
        "Black Heart Wasteland",
    ),
    "cloud_mountain" to listOf(
        "Serene Village",
        "Serene Hiking",
        "Cacodaemon Stockade",
        "The Wounded Camp",
        "Bamboo Forest of Cloud Mountain",
        "Centipede Mountain",
    ),
    "stone_city" to listOf(
        "Belvedere",
        "Barren Road of West Suburb",
        "Gangster Alley",
        "Green Bamboo Road",
        "Jade Nunnery",
        "Leud Temple",
        "Mushroom Village",
        "Stone City",
        "Stone City North",
        "Stone City South",
    ),
    "black_wind_camp" to listOf(
        "Wei's Village",
        "Outside Black Wind Camp",
        "Black Wind Camp",
        "Black Wind Camp Dungeon",
        "West Suburb of Stone City",
        "Arms Bear Residence",
        "Bothy",
    ),
    "laurel_mountain" to listOf(
        "Ancient Laurel Grounds",
        "Laurel Road",
        "Laurel Room",
        "Red Flower Cave",
        "Fencing Room",
        "Red Flower Alley",
        "Fortune Pond",
        "Fire Cloud Cave",
        "Lava Valley",
        "Laurel Woods",
        "Forest Plain",
        "Spring of Fortune Pond",
        "Fountain Plain",
    ),
    "alchemical_room" to listOf("Alchemical Room"),
    "snow_mountain" to listOf(
        "Snow Forrest",
        "Snow Village",
        "Ghost Shadow Swamp",
        "Ghost Wind Valley",
        "Trade Caravan Camp",
        "White Mountain Shrubberies",
        "White Mountain Cave",
        "Far Temple",
        "Outer Far Temple",
        "Riprap Hillock",
    ),
    "whorl_mountain" to listOf(
        "Ice Prick Forest",
        "Live Diagram Zone",
        "Floating Ice Area",
        "Hotspring Valley",
        "Death Diagram Zone",
        "Skull Hollow",
        "Throat Rift Stage",
        "Fiend Hall",
        "Arm Broken Bluff",
    ),
    "vast_mountain" to listOf(
        "White Bear Village",
        "Black Bear Cave",
        "Zhao's Palace",
        "Vast Mountain",
        "Wood Demon Cave",
        "Tusk Ogre Lair",
        "Ghost Din Woods",
    ),
    "dais_field" to listOf(
        "Yue Mansion",
        "Brier Woods",
        "Avenue",
        "Ling Mansion",
        "Star Town",
        "Chen's Manor",
        "Dai's Field",
        "Ichthyoid Cave",
        "Mazy Woods",
        "Market of Clear Water Dam",
        "New Field of Loo's Village",
        "Old Field of Loo's Village",
        "Jail of Screw Bay",
    ),
)

/** Port of `location_to_zone_map` — {location name: zone key}. */
val locationToZoneMap: Map<String, String> = zoneMap.entries
    .flatMap { (zone, locs) -> locs.map { it to zone } }
    .toMap()
