name: Build

on:
  workflow_call:

jobs:
  build-executables:
    uses: ./.github/workflows/build-executable.yml
    strategy:
      matrix:
        executable-kind: [client, server]
    with:
      executable_kind: ${{ matrix.executable-kind }}
