name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - staging
    tags: ['*']

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml

  build:
    needs:
      - test
    uses: ./.github/workflows/build.yml

  release:
    needs:
      - build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch_depth: 0

      - name: Debug contexts
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.event.ref_type: ${{ github.event.ref_type }}"
          echo "github.event.created: ${{ github.event.created }}" 
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.ref_type: ${{ github.ref_type }}"
          echo "runner.os: ${{ runner.os }}"

      - name: Download All Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: "*.exe"
          merge-multiple: true

      - name: 'Get Previous tag'
        if: github.event_name == 'push' && github.ref_type == 'tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v2"
        with:
          pattern: "*[0-9].*[0-9].*[0-9]"

#      - name: Detect previous SimVer release
#        id: vars
#        run: |
#           git fetch -a
#           echo ::set-output name=previous_major::$(git tag --sort "-committerdate" | grep -E "[0-9]" | cut -d$"\n" -f2)

      - name: Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref_type == 'tag'
        with:
          artifacts: "run_server.exe,run_client.exe"
          artifactErrorsFailBuild: true
          makeLatest: true
          generateReleaseNotes: true
          generateReleaseNotesPreviousTag: ${{ steps.previoustag.outputs.tag }}
          body: ${{ github.ref }}

      - name: Pre-Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref_name == 'master'
        with:
          artifacts: "run_server.exe,run_client.exe"
          artifactErrorsFailBuild: true
          name: pre-release
          body: pre-release build
          prerelease: true
          makeLatest: false
          tag: pre-release

      - name: Development Release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref_name == 'staging'
        with:
          artifacts: "run_server.exe,run_client.exe"
          artifactErrorsFailBuild: true
          name: latest
          body: development build
          prerelease: true
          makeLatest: false
          tag: development
